D# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Barbera dev
email: julian1barbera@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Games and other stuff created by Julian Barbera
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.barbera-dev.com" # the base hostname & protocol for your site
twitter_username: none
github_username:  fisheatpork

# Build settings
markdown: kramdown
